services:
    mindbird.picker.isotope_product_provider:
        class: Mindbird\IsotopeProductLink\Picker\ProductPickerProvider
        public: false
        arguments:
            - "@knp_menu.factory"
            - "@router"
        calls:
            - [setTokenStorage, ["@security.token_storage"]]
        tags:
            - { name: contao.picker_provider }